language: scala

scala:
  2.11.8

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash) -t 20835e30-7fc1-4d64-9bd4-7e2bcc51858e
